### ISSUE TITLE
Problem binding to an integer column

### ISSUE THREAD

**Issue by fwgreen** [vapor/nio-postgres#20]
I can't seem to bind to an `integer` numeric type column:
```sql
let id = PostgresData(int: 5)
conn.query("SELECT id, first_name, last_name FROM normal.person WHERE id=$1", [id]).wait()
```
```
NIOPostgres error: server error: incorrect binary data format in bind parameter 1 (exec_bind_message)
```
I've tried a few other integer types (`int16`, `uint16`,...) but nothing works.  

Swift 5.0-release, PostgreSQL 10.7, Ubuntu 18.04

**Comment by tanner0101** [comment]
Thanks, I'll take a look. Could you share the `CREATE` statement used for the `normal.person` table?

**Comment by fwgreen** [comment]
Here's my create statement:
```sql
create schema if not exists normal;
set search_path to normal;
create table person(id serial primary key, first_name text, last_name text);
```
This is what Postgres generates (if it helps):
```sql
CREATE TABLE normal.person
(
    id integer NOT NULL DEFAULT nextval('normal.person_id_seq'::regclass),
    first_name text COLLATE pg_catalog."default",
    last_name text COLLATE pg_catalog."default",
    CONSTRAINT person_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE normal.person
    OWNER to postgres;
```

**Comment by tanner0101** [comment]
Ah, I see. Thanks for the detailed response. `serial` is a 32-bit integer, so Postgres is giving a confusing error about the parameter not being the right width. Here are some solutions:

- Use `bigserial`
- Use `bigint` with `generated by default as primary key`
- Use `PostgresData(int32: 5)`

**Comment by fwgreen** [comment]
Option 3 did the trick with the least amount of hassle. Thanks for your help and for providing this elegant library.  Closing.
