### ISSUE TITLE
Attempt at NUMERIC conversion leads to crash

### ISSUE THREAD

**Issue by fwgreen** [vapor/nio-postgres#21]
I see NUMERIC isn't supported yet, but it's hard to tell when PostgreSQL will throw one at you without doing some digging.  Trying take an average:
```sql
select avg(length(content)) as average_length from message
```
leads to:
```
Fatal error: Cannot decode Double from 0x0005000000000010006d245e0d780ac6183f (NUMERIC): file /Users/fwgreen/Documents/SwiftProjects/MessageManager/.build/checkouts/nio-postgres/Sources/NIOPostgres/Data/PostgresData+Double.swift, line 19
Illegal instruction: 4
```
This workaround avoids the problem:
```sql
select cast(avg(length(content)) as double precision) as average_length from message
```

**Comment by tanner0101** [comment]
Indeed, numeric wasn't added yet. I've put up a PR here to add support for _read_ing NUMERIC. Support for binding double/numeric still needs to be added. https://github.com/vapor/nio-postgres/pull/23
