### ISSUE TITLE
remove row column tableOID parameter

### ISSUE THREAD

**Issue by tanner0101** [vapor/nio-postgres#24]
Currently `PostgresRow` let's you fetch a column for a given tableOID (UInt32). This is not really useful in practice and is holding us back from some optimizations that could improve decoding performance. I think we should consider removing this.

**Comment by MrMage** [comment]
See https://github.com/vapor/nio-postgres/pull/22#discussion_r278751054. But wouldn't removing that parameter cause problems with `JOIN`s where both tables have a column with the same name?

**Comment by tanner0101** [comment]
@MrMage in that case you can use aliases to disambiguate:

```sql
select foo.id as foo_id, bar.id as bar_id from foo join bar ...
```

Theoretically you could use the tableOID to do this, but in practice it is very difficult to do correctly. You must perform a query to select the oid for a given table name:

```sql
SELECT oid FROM pg_class WHERE relname = 'mytable'
```

Caching these values is also a burden as they may change any time the schema is altered.

**Comment by MrMage** [comment]
@tanner0101 thanks for the elaboration! Sort-of-related: If I were to use Fluent for the joins, would it automatically set the aliases as needed?

**Comment by tanner0101** [comment]
Yup, that's how Fluent 4 works on master now: 
https://github.com/vapor/fluent-kit/blob/master/Sources/FluentKit/Query/QueryBuilder.swift#L82
https://github.com/vapor/fluent-kit/blob/master/Sources/FluentKit/Model/EagerLoad.swift#L12

Fluent 3 did indeed use the tableOID + lookup method, which was a pain for the reasons I mentioned. Aliases seem like the better solution.
